title: gogitup
description: "Stop manually checking versions. Keep the tools you installed with go install updated with a single command."

remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jekyll-remote-theme

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.3"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: green

# External navigation links
nav_external_links:
  - title: gogitup on GitHub
    url: https://github.com/UnitVectorY-Labs/gogitup

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/gogitup"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"
